source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'lino', '~> 1.3'
gem 'rake_dependencies', '~> 2.5'
gem 'rake_terraform', '~> 1.9'
gem 'rake_docker', '~> 2.11'
gem 'rake_fly', '~> 1.11'
gem 'confidante', '~> 0.21'
gem 'docker-api', '~> 1.33'
gem 'semantic', '~> 1.6'
gem 'dotenv', '~> 2.7'
gem 'activesupport', '~> 6.0'
