source 'https://rubygems.org'

gem 'rake', '~> 12.3'
gem 'lino', '~> 1.1'
gem 'rake_dependencies', '~> 0.19'
gem 'rake_terraform', '~> 0.23'
gem 'rake_docker', '~> 0.17'
gem 'rake_fly', '~> 0.9'
gem 'confidante', '~> 0.6'
gem 'docker-api', '~> 1.33'
gem 'semantic', '~> 1.6'
gem 'dotenv', '~> 2.5'
gem 'activesupport', '~> 5.2'
