source 'https://rubygems.org'

gem 'rake', '~> 13.0'
gem 'lino', '~> 1.1'
gem 'rake_dependencies', '~> 0.23'
gem 'rake_terraform', '~> 0.31'
gem 'rake_docker', '~> 0.23'
gem 'rake_fly', '~> 0.21'
gem 'confidante', '~> 0.13'
gem 'docker-api', '~> 1.33'
gem 'semantic', '~> 1.6'
gem 'dotenv', '~> 2.7'
gem 'activesupport', '~> 6.0'
