---
region: "eu-west-1"
component: "concourse-example"

private_network_cidr: "10.0.0.0/16"

state_bucket_name: "infrablocks-%{hiera('component')}-%{hiera('deployment_identifier')}"
secrets_bucket_name: "%{hiera('state_bucket_name')}"

web_repository_name: "infrablocks/concourse-web"
worker_repository_name: "infrablocks/concourse-worker"

domain_state_bucket_region: "%{hiera('region')}"
domain_state_bucket_name: "%{hiera('state_bucket_name')}"
domain_state_bucket_is_encrypted: "true"
domain_state_key: "domain/deployments/%{hiera('deployment_identifier')}.tfstate"

network_state_bucket_region: "%{hiera('region')}"
network_state_bucket_name: "%{hiera('state_bucket_name')}"
network_state_bucket_is_encrypted: "true"
network_state_key: "network/deployments/%{hiera('deployment_identifier')}.tfstate"

web_image_repository_state_bucket_region: "%{hiera('region')}"
web_image_repository_state_bucket_name: "%{hiera('state_bucket_name')}"
web_image_repository_state_bucket_is_encrypted: "true"
web_image_repository_state_key: "web-image-repository/deployments/%{hiera('deployment_identifier')}.tfstate"

worker_image_repository_state_bucket_region: "%{hiera('region')}"
worker_image_repository_state_bucket_name: "%{hiera('state_bucket_name')}"
worker_image_repository_state_bucket_is_encrypted: "true"
worker_image_repository_state_key: "worker-image-repository/deployments/%{hiera('deployment_identifier')}.tfstate"

database_state_bucket_region: "%{hiera('region')}"
database_state_bucket_name: "%{hiera('state_bucket_name')}"
database_state_bucket_is_encrypted: "true"
database_state_key: "database/deployments/%{hiera('deployment_identifier')}.tfstate"

cluster_state_bucket_region: "%{hiera('region')}"
cluster_state_bucket_name: "%{hiera('state_bucket_name')}"
cluster_state_bucket_is_encrypted: "true"
cluster_state_key: "cluster/deployments/%{hiera('deployment_identifier')}.tfstate"

services_state_bucket_region: "%{hiera('region')}"
services_state_bucket_name: "%{hiera('state_bucket_name')}"
services_state_bucket_is_encrypted: "true"
services_state_key: "services/deployments/%{hiera('deployment_identifier')}.tfstate"
