---
region: "eu-west-1"
component: "concourse-example"

private_network_cidr: "10.0.0.0/16"

storage_bucket_name: "infrablocks-%{hiera('component')}-%{deployment_identifier}"
secrets_bucket_name: "%{hiera('storage_bucket_name')}"

web_repository_name: "infrablocks-examples/concourse-web"
worker_repository_name: "infrablocks-examples/concourse-worker"

domain_state_bucket_name: "%{hiera('storage_bucket_name')}"
domain_state_key: "domain/deployment-state/default.tfstate"
domain_state_bucket_region: "%{hiera('region')}"
domain_state_bucket_is_encrypted: "true"

certificate_state_bucket_name: "%{hiera('storage_bucket_name')}"
certificate_state_key: "certificate/deployment-state/default.tfstate"
certificate_state_bucket_region: "%{hiera('region')}"
certificate_state_bucket_is_encrypted: "true"

network_state_bucket_name: "%{hiera('storage_bucket_name')}"
network_state_key: "network/deployment-state/default.tfstate"
network_state_bucket_region: "%{hiera('region')}"
network_state_bucket_is_encrypted: "true"

web_image_repository_state_bucket_name: "%{hiera('storage_bucket_name')}"
web_image_repository_state_key: "web-image-repository/deployment-state/default.tfstate"
web_image_repository_state_bucket_region: "%{hiera('region')}"
web_image_repository_state_bucket_is_encrypted: "true"

worker_image_repository_state_bucket_name: "%{hiera('storage_bucket_name')}"
worker_image_repository_state_key: "worker-image-repository/deployment-state/default.tfstate"
worker_image_repository_state_bucket_region: "%{hiera('region')}"
worker_image_repository_state_bucket_is_encrypted: "true"

database_state_bucket_name: "%{hiera('storage_bucket_name')}"
database_state_key: "database/deployment-state/default.tfstate"
database_state_bucket_region: "%{hiera('region')}"
database_state_bucket_is_encrypted: "true"

cluster_state_bucket_name: "%{hiera('storage_bucket_name')}"
cluster_state_key: "cluster/deployment-state/default.tfstate"
cluster_state_bucket_region: "%{hiera('region')}"
cluster_state_bucket_is_encrypted: "true"

services_state_bucket_name: "%{hiera('storage_bucket_name')}"
services_state_key: "services/deployment-state/default.tfstate"
services_state_bucket_region: "%{hiera('region')}"
services_state_bucket_is_encrypted: "true"
