---
:backends:
  - "overrides"
  - "env"
  - "yaml"
:logger: "noop"
:yaml:
  :datadir: "config"
:hierarchy:
  - "roles/%{role}"
  - "secrets/concourse/web/example"
  - "secrets/database/example"
  - "defaults"
