---
vars:
  region: "%{hiera('region')}"
  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  private_network_cidr: "%{hiera('private_network_cidr')}"

  cluster_instance_ssh_public_key_path: "%{cwd}/config/secrets/cluster/ssh.public"
  cluster_instance_type: "t2.medium"

  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"
  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_bucket_is_encrypted: "%{hiera('network_state_bucket_is_encrypted')}"
  network_state_key: "%{hiera('network_state_key')}"

backend_config:
  region: "%{hiera('cluster_state_bucket_region')}"
  bucket: "%{hiera('cluster_state_bucket_name')}"
  encrypt: "%{hiera('cluster_state_bucket_is_encrypted')}"
  key: "%{hiera('cluster_state_key')}"
