---
vars:
  region: "%{hiera('region')}"
  private_network_cidr: "%{hiera('private_network_cidr')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  database_name: "%{hiera('database_name')}"
  database_username: "%{hiera('database_username')}"
  database_password: "%{hiera('database_password')}"

  network_state_bucket_region: "%{hiera('network_state_bucket_region')}"
  network_state_bucket_name: "%{hiera('network_state_bucket_name')}"
  network_state_bucket_is_encrypted: "%{hiera('network_state_bucket_is_encrypted')}"
  network_state_key: "%{hiera('network_state_key')}"

backend_config:
  region: "%{hiera('database_state_bucket_region')}"
  bucket: "%{hiera('database_state_bucket_name')}"
  encrypt: "%{hiera('database_state_bucket_is_encrypted')}"
  key: "%{hiera('database_state_key')}"
